### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fopina** [fopina/sublime-fispipstudio#2]
* [x] fispip package integration
* [x] Side bar and context menus
* [x] Settings management
* [x] File Extension handling in `is_visible`
* [x] Syntax highlighting
* [x] Custom MRPC for `Run PSL` and `Compile and Link`
* [x] Commands in pallete
* [ ] Deploy to package control
